---
- name: Ensure Zsh with dependencies are installed
  become: true
  ansible.builtin.package:
    name:
      - zsh
      - fzf
    state: latest

- name: Ensure zsh is the default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "/usr/bin/zsh"

- name: Checks if .zshrc file exists
  # For Windows targets, use the ansible.windows.win_stat module instead.
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zshrc_file_check_result

- name: Makes a backup of .zshrc file
  # For Windows targets, use the ansible.windows.win_copy module instead.
  # Only run if the file exists and is not a symlink
  when: >-
    zshrc_file_check_result.stat.exists
    and ((zshrc_file_check_result.stat.islnk is defined and not zshrc_file_check_result.stat.islnk)
    or (zshrc_file_check_result.stat.islnk is not defined))
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc-backup"
    mode: "u=rw,go=r"

- name: Create a symbolic link to home from the .zshrc file
  # For Windows targets, use the ansible.windows.win_file module instead.
  # Only run if the file doesn't exist or exists and is not a symlink
  when: >-
    not zshrc_file_check_result.stat.exists
    or zshrc_file_check_result.stat.exists and
    ((zshrc_file_check_result.stat.islnk is defined and not zshrc_file_check_result.stat.islnk)
    or (zshrc_file_check_result.stat.islnk is not defined))
  ansible.builtin.file:
    src: "{{ playbook_dir }}/zsh/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: true
