---
- name: Get NodeJS LTS install script from nodesource
  ansible.builtin.get_url:
    url: "https://deb.nodesource.com/setup_lts.x"
    dest: /tmp/setup_lts.x
    mode: "u=rw,go=r"

- name: Install nodesource repositories # noqa: command-instead-of-shell
  become: true
  ansible.builtin.shell: bash /tmp/setup_lts.x
  register: nodesource_install_response
  changed_when: false
  notify:
    - Remove nodesource install script

- name: Install Node.JS LTS
  become: true
  ansible.builtin.package:
    name: nodejs
    update_cache: true
    state: present
