---
- name: Checks if VS Code repo source list exists
  become: true
  # For Windows targets, use the ansible.windows.win_stat module instead.
  ansible.builtin.stat:
    path: "/etc/apt/sources.list.d/vscode.list"
  register: vscode_repo_source_list_check_result

- name: Makes a backup of VS Code repo source list file
  become: true
  # For Windows targets, use the ansible.windows.win_copy module instead.
  # Only run if the file exists
  when: vscode_repo_source_list_check_result.stat.exists
  ansible.builtin.copy:
    src: "/etc/apt/sources.list.d/vscode.list"
    dest: "/etc/apt/sources.list.d/bkp/vscode.list"
    mode: "u=rw,go=r"

- name: Deletes VS Code repo source list file
  become: true
  # For Windows targets, use the ansible.windows.win_file module instead.
  # Only run if the file exists
  when: vscode_repo_source_list_check_result.stat.exists
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/vscode.list"
    state: absent

- name: Checks if VS Code repo source list save exists
  become: true
  # For Windows targets, use the ansible.windows.win_stat module instead.
  ansible.builtin.stat:
    path: "/etc/apt/sources.list.d/vscode.list.save"
  register: vscode_repo_source_list_save_check_result

- name: Deletes VS Code repo source list save file
  become: true
  # For Windows targets, use the ansible.windows.win_file module instead.
  # Only run if the file exists, no need to backup this one
  when: vscode_repo_source_list_save_check_result.stat.exists
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/vscode.list.save"
    state: absent

- name: Add VS Code Repository
  become: true
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
    uris: "https://packages.microsoft.com/repos/code"
    suites: ["stable"]
    components: ["main"]
    state: present
    enabled: true

- name: Install VS Code
  become: true
  ansible.builtin.package:
    name: code
    update_cache: true
    state: present

- name: Set code as the default handler for text/plain
  community.general.gio_mime:
    mime_type: text/plain
    handler: code.desktop
