---
- name: Remove k9s .deb package
  ansible.builtin.file:
    path: /tmp/k9s_linux_amd64.deb
    state: absent

- name: Remove awscliv2 archive
  ansible.builtin.file:
    path: /tmp/awscliv2.zip
    state: absent

- name: Remove google chrome .deb package
  ansible.builtin.file:
    path: /tmp/google-chrome-stable_current_amd64.deb
    state: absent
