# code: language=ansible
---
- name: Install zsh, Oh My Zsh, dependencies and configurations
  hosts: localhost
  tasks:
    - name: Install stow and git
      ansible.builtin.package:
        name:
          - stow
          - git
        state: present
      become: true
