# code: language=ansible
---
- name: Install general dependencies and configurations
  hosts: localhost
  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name:
          - wget
          - curl
          - git
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - gnupg
          # - stow
        state: present
      become: true

- name: Install zsh, Oh My Zsh, dependencies and configurations
  import_playbook: shell.yaml

- name: Install and configure text editors/IDEs
  import_playbook: editors.yaml

- name: Install and configure apps
  import_playbook: apps.yaml

- name: Install extensions and configure GNOME
  import_playbook: gnome.yaml
