---
- name: Check awscliv2 installed version
  ansible.builtin.shell: "aws --version"
  ignore_errors: true
  changed_when: false
  register: awscliv2_check_result

- name: Get awscliv2 archive
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: /tmp/awscliv2.zip
    mode: "u=rw,go=r"

- name: Create temporary awscliv2 folder
  ansible.builtin.file:
    path: /tmp/awscliv2/
    state: directory
    mode: "u=rwx,go=rx"

- name: Extract to temporary path
  become: true
  changed_when: false
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/awscliv2/
  notify:
    - Remove awscliv2 archive

- name: Install awscliv2
  when: awscliv2_check_result.rc != 0
  ignore_errors: true
  ansible.builtin.shell: "/tmp/awscliv2/aws/install --install-dir {{ ansible_env.HOME }}/.local/share/aws-cli --bin-dir {{ ansible_env.HOME }}/.local/bin"

- name: Update awscliv2 if it is already installed
  when: awscliv2_check_result.rc == 0
  register: result
  changed_when: '"Found same AWS CLI version" not in result.stdout'
  ansible.builtin.shell: "/tmp/awscliv2/aws/install --install-dir {{ ansible_env.HOME }}/.local/share/aws-cli --bin-dir {{ ansible_env.HOME }}/.local/bin --update"

- name: Remove awscliv2 temporary folder
  become: true
  ansible.builtin.file:
    path: /tmp/awscliv2/
    state: absent
