---
- name: Check insomnia installed version
  ansible.builtin.shell: insomnia --version
  ignore_errors: true
  changed_when: false
  register: insomnia_check_result

- name: Get latest release of insomnia public repo
  when: insomnia_check_result.rc != 0
  community.general.github_release:
    user: Kong
    repo: insomnia
    action: latest_release
  register: insomnia_latest_release

- name: Extract version using regex_replace
  set_fact:
    insomnia_latest_release_tag: "{{ insomnia_latest_release.tag | regex_replace('^.*@', '') }}"

- name: Get insomnia deb package
  when: insomnia_check_result.rc != 0
  ansible.builtin.get_url:
    url: "https://github.com/Kong/insomnia/releases/download/{{ insomnia_latest_release.tag }}/Insomnia.Core-{{ insomnia_latest_release_tag }}.deb"
    dest: /tmp/insomnia_amd64.deb
    mode: "u=rw,go=r"

- name: Install insomnia .deb package
  when: insomnia_check_result.rc != 0
  become: true
  ansible.builtin.apt:
    deb: "/tmp/insomnia_amd64.deb"
  notify:
    - Remove insomnia .deb package

- name: Install or update insomnia package
  become: true
  ansible.builtin.package:
    name: insomnia
    state: latest
    update_cache: true
