---
- name: Install and configure wezterm
  ansible.builtin.import_tasks: wezterm.yaml

- name: Install and configure gh
  ansible.builtin.import_tasks: gh.yaml

- name: Install and configure kubectl
  ansible.builtin.import_tasks: kubectl.yaml

- name: Install and configure kubectx
  ansible.builtin.import_tasks: kubectx.yaml

- name: Install and configure k9s
  ansible.builtin.import_tasks: k9s.yaml

- name: Install and configure terraform, vault, vagrant, packer
  ansible.builtin.import_tasks: hashicorp.yaml

- name: Install and configure awscliv2
  ansible.builtin.import_tasks: awscliv2.yaml

- name: Install and configure rofi
  ansible.builtin.import_tasks: rofi.yaml

- name: Install and configure flameshot
  ansible.builtin.import_tasks: flameshot.yaml

- name: Install and configure chrome
  ansible.builtin.import_tasks: chrome.yaml

- name: Install and configure obs studio
  ansible.builtin.import_tasks: obs.yaml

- name: Install and configure bottom
  ansible.builtin.import_tasks: bottom.yaml

- name: Install and configure neofetch
  ansible.builtin.import_tasks: neofetch.yaml

- name: Install and configure insomnia
  ansible.builtin.import_tasks: insomnia.yaml

- name: Install and configure wireshark
  ansible.builtin.import_tasks: wireshark.yaml

- name: Install and configure docker
  ansible.builtin.import_tasks: docker.yaml

# - name: Install and configure cudatoolkit
  # ansible.builtin.import_tasks: cudatoolkit.yaml
